# Topics to cover
- print
- variables (strings, numbers)
- variables names (legal, illegal)
- mathematical expression (```/, *, +, -```)
- mathematical expression (eliminating ambiguity)
- concatenating text strings


# print 

```Print``` is keyword which used to display ```strings``` & ```number```
    which we write inside the ```paranthesis ()```

In [29]:
print("Hello world..!")

Hello world..!


In [30]:
print("Welcome to data science")

Welcome to data science


In [31]:
print("123")

123


Note: here ```123``` are in form of ```string```

In [32]:
print(1234) 

1234


Note: here ```1234``` are in form of ```integer```

# variable

```variable``` is the container which occupied space in memory to store values    in it. first you have to ```give variable a name```  and than assign values to it by write equal ```=``` to sign after giving name. 

In [33]:
name = "Rameez Ahmed"
print(name)

Rameez Ahmed


Note: ```name``` is name of variable which store ```string``` value = ```Rameez Ahmed```

In [34]:
age = 25
print(age)

25


Note: ```age``` is name of variable which store a ```integer``` value = ```25```

In [35]:
country = "Pakistan"
provence = "Sindh"
city = "Karachi"

print(country)
print(provence)
print(city)

Pakistan
Sindh
Karachi


In [36]:
print(name)
print(age)
print(country)
print(provence)
print(city)

Rameez Ahmed
25
Pakistan
Sindh
Karachi


In [37]:
age = 18
age+7


25

Note: So, what happend here!
here 7 is added to the age variable which have 18 as its value. so 7 is added 18 which means ```18+7=25```
also to note that```datatype of age is integer``` & ``` 7 is also a integer```

In [38]:
print(type(age)) # here we check type of variable by keyword "type" 

<class 'int'>


In [39]:
print(type(7)) # here we check type of variable by keyword "type"

<class 'int'>


In [40]:
print(type(name)) # here we check type of variable by keyword "type"

<class 'str'>


In [41]:
width = 10
height = 15
area = width * height

print(area)

150


# variable name rules

#### 1- variable name should be started with ```Alphabets (A-Z)``` or ```underscore ( _ )```

In [42]:
name = "Rameez Ahmed"
print(name)

Rameez Ahmed


In [43]:
_father_name = "Muhammad Sadique"

print(_father_name)

Muhammad Sadique


#### 2- variable name should not start with ```number```
```but you can use number at the end```

In [44]:
2address = "karachi"  # it generate error
address2 = "Hyderabad"
print(2address)

SyntaxError: invalid syntax (2408471997.py, line 1)

In [45]:
address2 = "hyderabad"
print(address2)

hyderabad


#### 3- ```do not use space``` between variable names , if you want separate variable name user ```_``` underscore

In [46]:
2 address =  "karachi" # it also generate error
print(2 address)

SyntaxError: invalid syntax (2160709396.py, line 1)

In [47]:
address_2 = "hello"
address2 = "hello2"

print(address_2)
print(address2)

hello
hello2


In [48]:
roll no = "26" # it generate error

print(roll no)

SyntaxError: invalid syntax (3149146557.py, line 1)

In [49]:
roll_no = "26" # it will work
print(roll_no)

26


#### 4- ```don't use python keywords``` as variable name
like ```print```, ```int``` ```type``` 

In [50]:
print = 24 # it generate error
print(print)

TypeError: 'int' object is not callable

#### 5- ```don't use special character``` as variable name
like ```dot . ```, ```slash /``` ```star *``` 

In [51]:
first.name = "Ali"
last.name = "Muhammad"



NameError: name 'first' is not defined

# mathematical expressions

```mathematical epressions``` are the arithmetic operator wich is use to perform calculations on numbers. their are four operator which are ```*``` ```/``` ```+``` ```-```

In [1]:
addition = 2 + 5
subtraction = 10-5
division = 4/2
multiplication = 3*3


In [2]:
print(addition)
print(subtraction)
print(division)
print(multiplication)

7
5
2.0
9


In [1]:
2-5+3

0

In [2]:
3-5+2

0

In [3]:
8+4-4

8

In [4]:
add =  (2+9)
add

11

In [5]:
divide = 4/2 # this will give answer in decimal if you put one slash
divide

2.0

In [6]:
divide = 4//2 # this will give answer in whole number if you put two slash
divide

2

In [7]:
multi = 4*2
multi

8

In [8]:
power = 8**2 # it used for the values (8x8 = 8^2) is for power 8^2 = 64
print(power)

power1 = 4**2 # 4^2 = 4x4 = 16
print(power1)

64
16


In [9]:
module = 10 % 2 # % is called as modular, which mean it is to find remainder values in division
module

0

In [10]:
module = 5 % 2
module

1

## Python Operators Precedence Rule – PEMDAS
- You might have heard about the ```BODMAS``` rule in your school’s mathematics class. Python also uses a similar type of rule known as ```PEMDAS```.

- P  ```Parentheses```
- E  ```Exponentiation```
- M  ```Multiplication```
- D  ```Division```
- A  ```Addition```
- S  ```Subtraction```

In [11]:
10-5/2   #according to ```PEMDAS``` rule, first division is perform 5/2 = 2.5 and then subtraction 10-2.5 = 7.5

7.5

In [12]:
10-5/5 # So, as there.

9.0

-  (10-5)/5  what will be output now..!
here first  we have to solve paranthesis after that we solve division

1.  (10-5) = 5

2.  5/5 = 1

In [13]:
(10-5)/5

1.0

## solve this equation = ```((((6+4)*2)-10)//2)-4*2```

#### ((((```6+4```)*2)-10)//2)-4*2
#### (((```10*2```)-10)//2)-4*2
#### ((```(20)-10```)//2)-4*2
#### (```(10//2```)-4*2
#### (```5```)-4*2
#### 5-```4*2```
#### ```5-8```
### answer = ```-3```

In [14]:
((((6+4)*2)-10)//2)-4*2


-3

## Concatenation in python

Concatenation is the technique of ```combining two strings```. String Concatenation can be done using many ways

- Using ```+``` operator 
 
- Using ```join()``` method 
 
- Using ```%``` operator 
 
- Using ```format()``` function 
 
- Using ```,``` (comma)

#### Using ```+``` operator

In [15]:
# lets create two variable and combine them together with + operator 
first_name = "Rameez"
last_name = "Ahmed"

# if you combine them, you have to create 3rd variable to store both varible's values.
full_name = first_name + last_name   # now both variable's value stored in full_name variable

In [16]:
print(full_name)

RameezAhmed


In [17]:
#as you noted full name doesn't have any space between them, so we have to create space between them by two quotation marks "  "

full_name = first_name + " " + last_name

print(full_name)

Rameez Ahmed


- can we combine age variable with name?

In [18]:
name = "Rameez Ahmed"
age = 25

name_age = name + age # can this run or generate error..? let print it another cell

print(name_age)

TypeError: can only concatenate str (not "int") to str

so, ```we can not combine or concatenate string to integer.```

but if ```we change the data-type of integer into string, our code will run```

In [19]:
# change data type of age-----> to string---------> str(age)

name = "Rameez Ahmed"
age = 25

name_age = name + " " + str(age) # here , we changed the data type of age from integer to string.
print(name_age)

Rameez Ahmed 25


#### Using ```join()``` method

lets take same example of name

In [20]:
first_name = "Shams"
last_name = "Tabrizi"

# here its depend on you to direct joint both values or store both variable to 3rd variable and then join them


#direct join and print result.
print("".join([first_name, last_name]))

# with space between names
print(" ".join([first_name, last_name]))



ShamsTabrizi
Shams Tabrizi


In [21]:
first_name = "Shams"
last_name = "Tabrizi"

# here its depend on you to direct joint both values or store both variable to 3rd variable and then join them

#create 3rd variable to store both values
full_name = "".join([first_name, last_name])
print(full_name)

#with space between names
full_name = " ".join([first_name, last_name])
print(full_name)


ShamsTabrizi
Shams Tabrizi


#### Using ```format()``` method

In [22]:
provence = "Sindh"
country = "Pakistan"


print("{} {}".format(provence, country))


#store values inside 3rd variables.

provence_state = "{} {}".format(provence, country)

print(provence_state)

Sindh Pakistan
Sindh Pakistan


#### Using ```, comma``` method

In [23]:
first_word = "Hello"
second_word = "World"

print(first_word,second_word)

Hello World


# Basic of python ends here.